# Generated by Django 5.0.6 on 2025-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='Expected_Payout',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreport',
            name='Payment_Mechanism_Fee',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreport',
            name='Service_Fee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreport',
            name='Taxes_on_Service_Payment_Fees',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
