# Generated by Django 5.0.6 on 2025-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0002_salesreport_expected_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zomatoorder',
            name='Order_level_Payout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zomatoorder',
            name='Settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zomatoorder',
            name='Unsettled_Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zomatoorder',
            name='fp_Dispute_Status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
