# Generated by Django 5.0.6 on 2025-03-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0003_alter_zomatoorder_order_level_payout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesReport',
            new_name='sales_report',
        ),
        migrations.RenameModel(
            old_name='ZomatoOrder',
            new_name='zomato_order',
        ),
    ]
