# Generated by Django 5.0.6 on 2025-03-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0004_rename_salesreport_sales_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zomato_order',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
