# Generated by Django 5.0.6 on 2025-03-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0005_alter_zomato_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_report',
        ),
        migrations.DeleteModel(
            name='zomato_order',
        ),
    ]
