# Generated by Django 5.0.6 on 2025-03-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0007_sales_report_zomato_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sales_orders', models.IntegerField()),
                ('total_zomato_orders', models.IntegerField()),
                ('missing_orders_count', models.IntegerField()),
                ('missing_orders', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('discrepancy', 'Discrepancy Found')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='Payout_Reconciliation.clientdetails')),
            ],
        ),
    ]
