# Generated by Django 5.0.6 on 2025-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0010_clientdetails_created_date_clientdetails_delflag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='created_date',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
