# Generated by Django 5.0.6 on 2025-03-08 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0012_alter_clientdetails_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
