# Generated by Django 5.0.6 on 2025-03-08 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0014_remove_clientdetails_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
