# Generated by Django 5.0.6 on 2025-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0017_remove_clientdetails_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
