# Generated by Django 5.0.6 on 2025-03-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0018_clientdetails_create_date_clientdetails_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='delflag',
        ),
    ]
