# Generated by Django 5.0.6 on 2025-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0019_remove_clientdetails_delflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='delflag',
            field=models.IntegerField(default=1),
        ),
    ]
