# Generated by Django 5.0.6 on 2025-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0020_clientdetails_delflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='postel_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
