# Generated by Django 5.0.6 on 2025-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0021_clientdetails_postel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='business_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Grocery', 'Grocery'), ('Meat Shop', 'Meat Shop'), ('Fruit Shop', 'Fruit Shop'), ('Vegetable Shop', 'Vegetable Shop'), ('E-commerce Seller', 'E-commerce Seller')], max_length=50),
        ),
    ]
