# Generated by Django 5.0.6 on 2025-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0024_alter_clientdetails_fe_escalation_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
