# Generated by Django 5.0.6 on 2025-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0025_alter_clientdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregator',
            name='delflag',
            field=models.IntegerField(default=1),
        ),
    ]
