# Generated by Django 5.0.6 on 2025-03-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0027_sales_report_swiggy_swiggyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsummary',
            name='aggregator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
