# Generated by Django 5.0.6 on 2025-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0028_reconciliationsummary_aggregator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconciliationsummary',
            old_name='total_zomato_orders',
            new_name='total_orders',
        ),
    ]
