# Generated by Django 5.0.6 on 2025-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0030_reconciliationsummary_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationsummary',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='reconciliationsummary',
            name='to_date',
        ),
    ]
