# Generated by Django 5.0.6 on 2025-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0031_remove_reconciliationsummary_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsummary',
            name='from_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationsummary',
            name='to_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
