# Generated by Django 5.0.6 on 2025-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0033_alter_reconciliationsummary_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='actual_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='expected_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='missing_orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reconciliationsummary',
            name='total_sales_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationsummary',
            unique_together={('client_name', 'aggregator', 'from_date', 'to_date')},
        ),
    ]
