# Generated by Django 5.0.6 on 2025-03-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0034_alter_reconciliationsummary_actual_payout_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reconciliationsummary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reconciliationsummary',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='reconciliationsummary',
            name='to_date',
        ),
    ]
