# Generated by Django 5.0.6 on 2025-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0035_alter_reconciliationsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsummary',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationsummary',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationsummary',
            unique_together={('client_name', 'aggregator', 'from_date', 'to_date')},
        ),
    ]
