# Generated by Django 5.0.6 on 2025-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0036_reconciliationsummary_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='Net_Bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='Net_Bill_GST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales_report_swiggy',
            name='Expected_Payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_report_swiggy',
            name='Payment_Mechanism_Fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_report_swiggy',
            name='Service_Fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_report_swiggy',
            name='Taxes_on_Service_Payment_Fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
