# Generated by Django 5.0.6 on 2025-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0037_sales_report_swiggy_net_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_report_swiggy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
