# Generated by Django 5.0.6 on 2025-03-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0038_alter_sales_report_swiggy_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_report_swiggy',
            name='Net_Bill',
        ),
    ]
