# Generated by Django 5.0.6 on 2025-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0039_remove_sales_report_swiggy_net_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='Net_Bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
