# Generated by Django 5.0.6 on 2025-03-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0040_sales_report_swiggy_net_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Net_Bill',
            new_name='Net_Bill_cal',
        ),
    ]
