# Generated by Django 5.0.6 on 2025-03-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0041_rename_net_bill_sales_report_swiggy_net_bill_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_report_swiggy',
            name='Net_Bill_cal',
        ),
    ]
