# Generated by Django 5.0.6 on 2025-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0042_remove_sales_report_swiggy_net_bill_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_report_swiggy',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='Net_Bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
