# Generated by Django 5.0.6 on 2025-03-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0044_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payout_Reconciliation.membership'),
        ),
    ]
