# Generated by Django 5.0.6 on 2025-03-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0045_alter_clientdetails_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='membership_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'delflag': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payout_Reconciliation.membership'),
        ),
    ]
