# Generated by Django 5.0.6 on 2025-03-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0046_alter_clientdetails_membership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_report',
            old_name='Expected_Payout',
            new_name='fp_Expected_Payout',
        ),
        migrations.RenameField(
            model_name='sales_report',
            old_name='Payment_Mechanism_Fee',
            new_name='fp_Payment_Mechanism_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report',
            old_name='Service_Fee',
            new_name='fp_Service_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report',
            old_name='Taxes_on_Service_Payment_Fees',
            new_name='fp_Taxes_on_Service_Payment_Fees',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Expected_Payout',
            new_name='fp_Expected_Payout',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Net_Bill',
            new_name='fp_Net_Bill',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Net_Bill_GST',
            new_name='fp_Net_Bill_GST',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Payment_Mechanism_Fee',
            new_name='fp_Payment_Mechanism_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Service_Fee',
            new_name='fp_Service_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report_swiggy',
            old_name='Taxes_on_Service_Payment_Fees',
            new_name='fp_Taxes_on_Service_Payment_Fees',
        ),
    ]
