# Generated by Django 5.0.6 on 2025-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0047_rename_expected_payout_sales_report_fp_expected_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_report',
            name='fp_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
