# Generated by Django 5.0.6 on 2025-03-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0049_clientdetails_fe_commision_pre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='fe_commision_pre',
            new_name='fe_commission_pre',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='sw_commision_pre',
            new_name='sw_commission_pre',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='zo_commision_pre',
            new_name='zo_commission_pre',
        ),
    ]
