# Generated by Django 5.0.6 on 2025-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0050_rename_fe_commision_pre_clientdetails_fe_commission_pre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='fp_res_id',
            new_name='swiggy_res_id',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='zomato_res_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
