# Generated by Django 5.0.6 on 2025-03-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0052_clientdetails_flyereats_res_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients_zomato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Payout_Reconciliation.clientdetails')),
                ('fp_zo_res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zomatoclients', to='Payout_Reconciliation.clientdetails')),
            ],
        ),
    ]
