# Generated by Django 5.0.6 on 2025-03-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0054_alter_clients_zomato_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='fe_commission_pre',
            new_name='flyereats_commission_pre',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='flyereats_res_id',
            new_name='flyereats_restaurant_id',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='sw_commission_pre',
            new_name='swiggy_commission_pre',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='swiggy_res_id',
            new_name='swiggy_restaurant_id',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='zo_commission_pre',
            new_name='zomato_commission_pre',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='zomato_res_id',
            new_name='zomato_restaurant_id',
        ),
    ]
