# Generated by Django 5.0.6 on 2025-03-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0055_rename_fe_commission_pre_clientdetails_flyereats_commission_pre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_report',
            name='fp_restaurant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
