# Generated by Django 5.0.6 on 2025-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0056_sales_report_fp_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zomato_order',
            name='fp_restaurant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
