# Generated by Django 5.0.6 on 2025-03-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0057_zomato_order_fp_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients_zomato',
            old_name='fp_zo_res_id',
            new_name='fp_restaurant_id',
        ),
    ]
