# Generated by Django 5.0.6 on 2025-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0058_rename_fp_zo_res_id_clients_zomato_fp_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsummary',
            name='restaurant_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
