# Generated by Django 5.0.6 on 2025-03-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0059_reconciliationsummary_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='email_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
