# Generated by Django 5.0.6 on 2025-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0060_clientdetails_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='swiggy_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='zomato_tax',
            field=models.BooleanField(default=False),
        ),
    ]
