# Generated by Django 5.0.6 on 2025-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0061_clientdetails_swiggy_tax_clientdetails_zomato_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='flyereats_tax',
            field=models.BooleanField(default=False),
        ),
    ]
