# Generated by Django 5.0.6 on 2025-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0062_clientdetails_flyereats_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients_swiggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('fp_restaurant_id', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
            ],
        ),
    ]
