# Generated by Django 5.0.6 on 2025-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0063_clients_swiggy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='fp_restaurant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_report_swiggy',
            name='fp_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
