# Generated by Django 5.0.6 on 2025-03-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0064_sales_report_swiggy_fp_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='flyereats_commission_pre',
            new_name='flyereats_commission_percentage',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='swiggy_commission_pre',
            new_name='swiggy_commission_percentage',
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='zomato_commission_pre',
            new_name='zomato_commission_percentage',
        ),
    ]
