# Generated by Django 5.0.6 on 2025-03-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0065_rename_flyereats_commission_pre_clientdetails_flyereats_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiggyorder',
            name='fp_restaurant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
