# Generated by Django 5.0.6 on 2025-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0066_swiggyorder_fp_restaurant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='swiggy_CPC_Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('fp_restaurant_id', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('cpc_value', models.CharField(max_length=20)),
            ],
        ),
    ]
