# Generated by Django 5.0.6 on 2025-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0067_swiggy_cpc_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiggy_cpc_ads',
            name='cpc_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
