# Generated by Django 5.0.6 on 2025-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0068_alter_swiggy_cpc_ads_cpc_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='zomato_cpc_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('fp_restaurant_id', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('total_ads_inc_gst', models.CharField(max_length=20)),
                ('total_dining_ads', models.CharField(max_length=20)),
                ('total_cpc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='swiggy_cpc_ads',
            unique_together={('from_date', 'to_date', 'fp_restaurant_id', 'client_name', 'cpc_value')},
        ),
    ]
