# Generated by Django 5.0.6 on 2025-03-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0070_alter_zomato_cpc_ads_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zomato_cpc_ads',
            old_name='total_cpc',
            new_name='cpc_value',
        ),
        migrations.AlterUniqueTogether(
            name='zomato_cpc_ads',
            unique_together={('from_date', 'to_date', 'fp_restaurant_id', 'client_name', 'total_ads_inc_gst', 'total_dining_ads', 'cpc_value')},
        ),
    ]
