# Generated by Django 5.0.6 on 2025-03-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0072_alter_zomato_cpc_ads_cpc_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='aggregator_payment_mechanism_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
