# Generated by Django 5.0.6 on 2025-03-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0073_aggregator_aggregator_payment_mechanism_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregator',
            old_name='aggregator_payment_mechanism_fee',
            new_name='payment_mechanism_fee',
        ),
    ]
