# Generated by Django 5.0.6 on 2025-04-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0075_aggregator_payment_mechanism_fee_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='create_date',
        ),
    ]
