# Generated by Django 5.0.6 on 2025-04-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0075_aggregator_payment_mechanism_fee_online'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales_report',
            new_name='sales_report_zomato',
        ),
    ]
