# Generated by Django 5.0.6 on 2025-04-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0076_rename_sales_report_sales_report_zomato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zomato_order',
            name='fp_Dispute_Status',
        ),
    ]
