# Generated by Django 5.0.6 on 2025-04-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0077_remove_zomato_order_fp_dispute_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_report_zomato',
            old_name='fp_Client_Name',
            new_name='Client_Name',
        ),
        migrations.RenameField(
            model_name='sales_report_zomato',
            old_name='fp_Expected_Payout',
            new_name='Expected_Payout',
        ),
        migrations.RenameField(
            model_name='sales_report_zomato',
            old_name='fp_Payment_Mechanism_Fee',
            new_name='Payment_Mechanism_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report_zomato',
            old_name='fp_Service_Fee',
            new_name='Service_Fee',
        ),
        migrations.RenameField(
            model_name='sales_report_zomato',
            old_name='fp_Taxes_on_Service_Payment_Fees',
            new_name='Taxes_on_Service_Payment_Fees',
        ),
    ]
