# Generated by Django 5.0.6 on 2025-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0080_sentemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemaillog',
            name='aggregator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemaillog',
            name='restaurant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
