# Generated by Django 5.0.6 on 2025-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0081_sentemaillog_aggregator_sentemaillog_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemaillog',
            name='date_range',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
