# Generated by Django 5.0.6 on 2025-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0082_sentemaillog_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemaillog',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
