# Generated by Django 5.0.6 on 2025-04-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0083_sentemaillog_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummeryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=255)),
                ('aggregator', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('wrong_payout_settled', models.CharField(default='-', max_length=10)),
                ('wrong_taxes_on_service_payment_fees', models.TextField(default='-')),
                ('wrong_payment_mechanism_fee', models.TextField(default='-')),
                ('wrong_service_fee', models.TextField(default='-')),
                ('cancelled_order_amount_deducted_wrongly', models.TextField(default='-')),
                ('TDS_issue', models.TextField(default='-')),
                ('Wrong_penalty', models.TextField(default='-')),
                ('fp_order_date', models.CharField(default='-', max_length=100)),
                ('fp_status', models.CharField(default='-', max_length=100)),
                ('missing_order_with', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
