# Generated by Django 5.0.6 on 2025-04-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0084_summerylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summerylog',
            unique_together={('order_id', 'restaurant_id', 'aggregator', 'fp_status')},
        ),
    ]
