# Generated by Django 5.0.6 on 2025-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0085_alter_summerylog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerylog',
            name='aggregator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summerylog',
            name='fp_status',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='summerylog',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summerylog',
            name='restaurant_id',
            field=models.CharField(max_length=100),
        ),
    ]
