# Generated by Django 5.0.6 on 2025-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0086_alter_summerylog_aggregator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerylog',
            name='aggregator',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='summerylog',
            name='restaurant_id',
            field=models.CharField(max_length=64),
        ),
    ]
