# Generated by Django 5.0.6 on 2025-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0088_alter_summerylog_order_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summerylog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='summerylog',
            name='restaurant_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='summerylog',
            unique_together={('order_id', 'restaurant_id', 'fp_status')},
        ),
    ]
