# Generated by Django 5.0.6 on 2025-04-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0091_emailreplylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Payout_Reconciliation.sentemaillog')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailReplyLog',
        ),
    ]
