# Generated by Django 5.0.6 on 2025-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0092_emailconversation_delete_emailreplylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemaillog',
            name='replies_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sentemaillog',
            name='user_replies_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
