# Generated by Django 5.0.6 on 2025-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0094_alter_summerylog_fp_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerylog',
            name='fp_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
