# Generated by Django 5.0.6 on 2025-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0095_alter_summerylog_fp_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='business_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Grocery', 'Grocery'), ('Meat Shop', 'Meat Shop'), ('Fruit Shop', 'Fruit Shop'), ('Vegetable Shop', 'Vegetable Shop'), ('E-commerce Seller', 'E-commerce Seller'), ('Quick-commerce Seller', 'Quick-commerce Seller')], max_length=50),
        ),
    ]
