# Generated by Django 5.0.6 on 2025-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0096_alter_clientdetails_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Existing user', 'Existing user'), ('New user', 'New user')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
