# Generated by Django 5.0.6 on 2025-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0097_demorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='reason',
            field=models.CharField(choices=[('book-demo', 'Book demo'), ('onboarding', 'New Merchant onboarding'), ('client-queries', 'Existing Client Queries'), ('feedback', 'General Feedback'), ('investor', 'Investor Relations')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
