# Generated by Django 5.0.6 on 2025-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0098_demorequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
