# Generated by Django 5.0.6 on 2025-04-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0099_demorequest_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='user_type',
        ),
    ]
