# Generated by Django 5.0.6 on 2025-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0100_remove_demorequest_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='country_code',
        ),
    ]
