# Generated by Django 5.0.6 on 2025-04-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0101_remove_demorequest_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='fp_password',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='fp_username',
        ),
    ]
