# Generated by Django 5.0.6 on 2025-04-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payout_Reconciliation', '0105_popuplead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='name',
            new_name='user_type',
        ),
    ]
